pub enum TextureUnit {
    Texture0,
    Texture1,
    Texture2,
    Texture3,
    Texture4,
    Texture5,
    Texture6,
    Texture7,
    Texture8,
    Texture9,
    Texture10,
    Texture11,
    Texture12,
    Texture13,
    Texture14,
    Texture15,
    Texture16,
    Texture17,
    Texture18,
    Texture19,
    Texture20,
    Texture21,
    Texture22,
    Texture23,
    Texture24,
    Texture25,
    Texture26,
    Texture27,
    Texture28,
    Texture29,
    Texture30,
    Texture31,
}

impl TextureUnit {
    pub fn to_u32(self) -> u32 {
        match self {
            TextureUnit::Texture0 => glow::TEXTURE0,
            TextureUnit::Texture1 => glow::TEXTURE1,
            TextureUnit::Texture2 => glow::TEXTURE2,
            TextureUnit::Texture3 => glow::TEXTURE3,
            TextureUnit::Texture4 => glow::TEXTURE4,
            TextureUnit::Texture5 => glow::TEXTURE5,
            TextureUnit::Texture6 => glow::TEXTURE6,
            TextureUnit::Texture7 => glow::TEXTURE7,
            TextureUnit::Texture8 => glow::TEXTURE8,
            TextureUnit::Texture9 => glow::TEXTURE9,
            TextureUnit::Texture10 => glow::TEXTURE10,
            TextureUnit::Texture11 => glow::TEXTURE11,
            TextureUnit::Texture12 => glow::TEXTURE12,
            TextureUnit::Texture13 => glow::TEXTURE13,
            TextureUnit::Texture14 => glow::TEXTURE14,
            TextureUnit::Texture15 => glow::TEXTURE15,
            TextureUnit::Texture16 => glow::TEXTURE16,
            TextureUnit::Texture17 => glow::TEXTURE17,
            TextureUnit::Texture18 => glow::TEXTURE18,
            TextureUnit::Texture19 => glow::TEXTURE19,
            TextureUnit::Texture20 => glow::TEXTURE20,
            TextureUnit::Texture21 => glow::TEXTURE21,
            TextureUnit::Texture22 => glow::TEXTURE22,
            TextureUnit::Texture23 => glow::TEXTURE23,
            TextureUnit::Texture24 => glow::TEXTURE24,
            TextureUnit::Texture25 => glow::TEXTURE25,
            TextureUnit::Texture26 => glow::TEXTURE26,
            TextureUnit::Texture27 => glow::TEXTURE27,
            TextureUnit::Texture28 => glow::TEXTURE28,
            TextureUnit::Texture29 => glow::TEXTURE29,
            TextureUnit::Texture30 => glow::TEXTURE30,
            TextureUnit::Texture31 => glow::TEXTURE31
        }
    }
}